### ISSUE TITLE
酷狗音乐获取音乐详情失败

### ISSUE THREAD

**Issue by jicanghai37927** [messoer/mess-api-doc#11]
https://v1.itooi.cn/kugou/song?id=706c25f9ccf316ff68371e16dc788dce

王力宏、任家萱 - 你是我心内的一首歌-706c25f9ccf316ff68371e16dc788dce

{"code":400,"msg":"获取数据失败","timestamp":1564630296698}

另外，相同的ID可以获取到歌词。
https://v1.itooi.cn/kugou/lrc?id=706c25f9ccf316ff68371e16dc788dce

**Comment by mrdong916** [comment]
已经修复了，付费歌曲无法获取
