### ISSUE TITLE
 网易云音乐视频搜索报错

### ISSUE THREAD

**Issue by Awes0mePy** [messoer/mess-api-doc#14]
https://v1.itooi.cn/netease/search?keyword=%E6%97%A0%E5%90%8D%E4%B9%8B%E8%BE%88&type=video&pageSize=100&page=0
{"code":400,"msg":"搜索类型不存在","timestamp":1565321635924}

type=mv  也不行跟网页搜索结果不一致

**Comment by mrdong916** [comment]
已经修复，下个版本更新
