### ISSUE TITLE
qq音乐：用户歌单信息

### ISSUE THREAD

**Issue by WuLianN** [messoer/mess-api-doc#19]
code: 400
msg: "https://c.y.qq.com/r/d6Cz?_wv=8192&validatetype=1&appid=1600000886&uid=0&lang=2052&apptype=0&captype=4&disturblevel=1"
timestamp: 1565671889703

点击msg验证，然后不了了之。
uid 我填的是 7w6z7KSkoe-P，应该不是这里出错吧。

**Comment by mrdong916** [comment]
接口出现问体，请等待修复此接口

**Comment by mrdong916** [comment]
已修复
