### ISSUE TITLE
QQ音乐获取播放链接错误

### ISSUE THREAD

**Issue by NiTian1207** [messoer/mess-api-doc#9]
https://v1.itooi.cn/tencent/url?id=003yMB404Bj7rm&quality=192
这个歌曲好像只有192的音质
其他的音质就会出现错误,不会自动跳转
![L4OI9GMZ_2EZRE)K{I{_19J](https://user-images.githubusercontent.com/40469236/62226438-d04ef500-b3ec-11e9-9192-44b3c7fe2194.png)

**Comment by mrdong916** [comment]
已修复
